AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Creates snapshot of each EC2 instance '
Resources:
  ebscreatesnapshots:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: 'Creates snapshot of each EC2 instance '
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::YOUR ACCOUNT NUMBER:role/lambda_ebs_backup'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(15 8 * * ? *)
